project:
  title: "ProbAI"

author:
  - name: Patrick Altmeyer
    url: https://www.paltmeyer.com/
    affiliation: Delft University of Technology
    affiliation-url: https://www.tudelft.nl/en/

bibliography: https://raw.githubusercontent.com/pat-alt/bib/main/bib.bib



